// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EfCoreModelsLib.Models;

[Index("Attribute1", Name = "attribute_UNIQUE", IsUnique = true)]
public partial class Attribute
{
    [Key]
    [Column("attribute_id")]
    public Guid AttributeId { get; set; }

    [Required]
    [Column("attribute")]
    [StringLength(100)]
    public string Attribute1 { get; set; }

    [ForeignKey("AttributesAttributeId")]
    [InverseProperty("AttributesAttributes")]
    public virtual ICollection<Alias> AliasesAliases { get; set; } = new List<Alias>();
}