// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EfCoreModelsLib.Models.Mysql;

[PrimaryKey("ActorId", "TitlesTitleId", "PersonsPersonId")]
[Index("PersonsPersonId", Name = "fk_Titles_has_Persons_Persons3_idx")]
[Index("TitlesTitleId", Name = "fk_Titles_has_Persons_Titles3_idx")]
public partial class Actors
{
    [Key]
    [Column("actor_id")]
    [MySqlCharSet("ascii")]
    [MySqlCollation("ascii_general_ci")]
    public Guid ActorId { get; set; }

    [Key]
    [Column("Titles_title_id")]
    [MySqlCharSet("ascii")]
    [MySqlCollation("ascii_general_ci")]
    public Guid TitlesTitleId { get; set; }

    [Key]
    [Column("Persons_person_id")]
    [MySqlCharSet("ascii")]
    [MySqlCollation("ascii_general_ci")]
    public Guid PersonsPersonId { get; set; }

    [Required]
    [StringLength(255)]
    public string Role { get; set; }

    [ForeignKey("PersonsPersonId")]
    [InverseProperty("Actors")]
    public virtual Persons PersonsPerson { get; set; }

    [ForeignKey("TitlesTitleId")]
    [InverseProperty("Actors")]
    public virtual Titles TitlesTitle { get; set; }
}