// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EfCoreModelsLib.Models.Mysql;

[Index("PersonId", Name = "fk_Professions_Persons1_idx")]
[Index("Profession", Name = "profession_UNIQUE", IsUnique = true)]
public partial class Professions
{
    [Key]
    [Column("profession_id")]
    [MySqlCharSet("ascii")]
    [MySqlCollation("ascii_general_ci")]
    public Guid ProfessionId { get; set; }

    [Column("person_id")]
    [MySqlCharSet("ascii")]
    [MySqlCollation("ascii_general_ci")]
    public Guid PersonId { get; set; }

    [Required]
    [Column("profession")]
    [StringLength(45)]
    public string Profession { get; set; }

    [ForeignKey("PersonId")]
    [InverseProperty("Professions")]
    public virtual Persons Person { get; set; }
}