// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EfCoreModelsLib.Models.Mysql;

[Keyless]
public partial class TitlesView
{
    [Column("title_id")]
    [MySqlCharSet("ascii")]
    [MySqlCollation("ascii_general_ci")]
    public Guid TitleId { get; set; }

    [Required]
    [Column("title_type")]
    [StringLength(100)]
    public string TitleType { get; set; }

    [Required]
    [Column("primary_title")]
    [StringLength(255)]
    public string PrimaryTitle { get; set; }

    [Required]
    [Column("original_title")]
    [StringLength(255)]
    public string OriginalTitle { get; set; }

    [Column("is_adult")]
    public bool IsAdult { get; set; }

    [Column("start_year")]
    public int StartYear { get; set; }

    [Column("runtime_minutes")]
    public int? RuntimeMinutes { get; set; }
}