// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EfCoreModelsLib.Models.Mysql;

[Index("Attribute", Name = "attribute_UNIQUE", IsUnique = true)]
public partial class Attributes
{
    [Key]
    [Column("attribute_id")]
    [MySqlCharSet("ascii")]
    [MySqlCollation("ascii_general_ci")]
    public Guid AttributeId { get; set; }

    [Required]
    [Column("attribute")]
    [StringLength(100)]
    public string Attribute { get; set; }

    [ForeignKey("AttributesAttributeId")]
    [InverseProperty("AttributesAttribute")]
    public virtual ICollection<Aliases> AliasesAlias { get; set; } = new List<Aliases>();
}