// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EfCoreModelsLib.Models.Mysql;

[Index("TitleId", Name = "fk_title_comments_title_basics1_idx")]
public partial class Comments
{
    [Key]
    [Column("comment_id")]
    public Guid CommentId { get; set; }

    [Column("title_id")]
    public Guid TitleId { get; set; }

    [Required]
    [Column("comment")]
    [StringLength(255)]
    public string Comment { get; set; }

    [ForeignKey("TitleId")]
    [InverseProperty("Comments")]
    public virtual Titles Title { get; set; }

    // Consider adding userId and CreateAt
    // public Guid UserId { get; set; }
    // public DateTime CreatedAt { get; set; }
}