// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EfCoreModelsLib.Models.Mysql;

[PrimaryKey("DirectorsId", "TitlesTitleId", "PersonsPersonId")]
[Index("PersonsPersonId", Name = "fk_Titles_has_Persons_Persons1_idx")]
[Index("TitlesTitleId", Name = "fk_Titles_has_Persons_Titles1_idx")]
public partial class Directors
{
    [Key]
    [Column("directors_id")]
    public Guid DirectorsId { get; set; }

    [Key]
    [Column("Titles_title_id")]
    public Guid TitlesTitleId { get; set; }

    [Key]
    [Column("Persons_person_id")]
    public Guid PersonsPersonId { get; set; }

    [ForeignKey("PersonsPersonId")]
    [InverseProperty("Directors")]
    public virtual Persons PersonsPerson { get; set; }

    [ForeignKey("TitlesTitleId")]
    [InverseProperty("Directors")]
    public virtual Titles TitlesTitle { get; set; }
}