// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EfCoreModelsLib.Models.Mysql;

[Index("TitleIdParent", Name = "fk_title_episodes_title_basics1")]
[Index("TitleIdChild", Name = "fk_title_episodes_title_basics2_idx")]
public partial class Episodes
{
    [Key]
    [Column("episode_id")]
    public Guid EpisodeId { get; set; }

    [Column("title_id_parent")]
    public Guid TitleIdParent { get; set; }

    [Column("title_id_child")]
    public Guid TitleIdChild { get; set; }

    [Column("season_number")]
    public int SeasonNumber { get; set; }

    [Column("episode_number")]
    public int EpisodeNumber { get; set; }

    [ForeignKey("TitleIdChild")]
    [InverseProperty("EpisodesTitleIdChildNavigation")]
    public virtual Titles TitleIdChildNavigation { get; set; }

    [ForeignKey("TitleIdParent")]
    [InverseProperty("EpisodesTitleIdParentNavigation")]
    public virtual Titles TitleIdParentNavigation { get; set; }
}