// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EfCoreModelsLib.Models.Mysql;

[Index("Genre", Name = "genre_UNIQUE", IsUnique = true)]
public partial class Genres
{
    [Key]
    [Column("genre_id")]
    public Guid GenreId { get; set; }

    [Required]
    [Column("genre")]
    [StringLength(100)]
    public string Genre { get; set; }

    [ForeignKey("GenresGenreId")]
    [InverseProperty("GenresGenre")]
    public virtual ICollection<Titles> TitlesTitle { get; set; } = new List<Titles>();
}