// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EfCoreModelsLib.Models.Mysql;

[Index("ExecutedAt", Name = "executed_at_index")]
[Index("TableName", Name = "table_name_index")]
public partial class Logging
{
    [Key]
    [Column("logging_id")]
    public Guid LoggingId { get; set; }

    [Column("table_name")]
    public Guid TableName { get; set; }

    [Required]
    [Column("command", TypeName = "enum('INSERT','UPDATE','DELETE')")]
    public string Command { get; set; }

    [Column("new_value", TypeName = "json")]
    public string NewValue { get; set; }

    [Column("old_value", TypeName = "json")]
    public string OldValue { get; set; }

    [Column("executed_by")]
    [StringLength(100)]
    public string ExecutedBy { get; set; }

    [Column("executed_at")]
    [MaxLength(6)]
    public DateTime ExecutedAt { get; set; }
}