// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EfCoreModelsLib.Models.Mysql;

public partial class Person
{
    [Key]
    [Column("person_id")]
    public Guid PersonId { get; set; }

    [Required]
    [Column("name")]
    [StringLength(255)]
    public string Name { get; set; }

    [Column("birth_year")]
    public int BirthYear { get; set; }

    [Column("end_year")]
    public int? EndYear { get; set; }

    [InverseProperty("PersonsPerson")]
    public virtual ICollection<Actor> Actors { get; set; } = new List<Actor>();

    [InverseProperty("Person")]
    public virtual ICollection<Profession> Professions { get; set; } = new List<Profession>();

    [ForeignKey("PersonsPersonId")]
    [InverseProperty("PersonsPeople")]
    public virtual ICollection<Title> TitlesTitles { get; set; } = new List<Title>();

    [ForeignKey("PersonsPersonId")]
    [InverseProperty("PersonsPeople1")]
    public virtual ICollection<Title> TitlesTitles1 { get; set; } = new List<Title>();

    [ForeignKey("PersonsPersonId")]
    [InverseProperty("PersonsPeopleNavigation")]
    public virtual ICollection<Title> TitlesTitlesNavigation { get; set; } = new List<Title>();
}