// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EfCoreModelsLib.Models.Mysql;

public partial class Persons
{
    [Key]
    [Column("person_id")]
    public Guid PersonId { get; set; }

    [Required]
    [Column("name")]
    [StringLength(255)]
    public string Name { get; set; }

    [Column("birth_year")]
    public int BirthYear { get; set; }

    [Column("end_year")]
    public int? EndYear { get; set; }

    [InverseProperty("PersonsPerson")]
    public virtual ICollection<Actors> Actors { get; set; } = new List<Actors>();

    [InverseProperty("PersonsPerson")]
    public virtual ICollection<Directors> Directors { get; set; } = new List<Directors>();

    [InverseProperty("PersonsPerson")]
    public virtual ICollection<KnownFor> KnownFor { get; set; } = new List<KnownFor>();

    [InverseProperty("Person")]
    public virtual ICollection<Professions> Professions { get; set; } = new List<Professions>();

    [InverseProperty("PersonsPerson")]
    public virtual ICollection<Writers> Writers { get; set; } = new List<Writers>();
}