// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EfCoreModelsLib.Models.Mysql;

[Index("Type", Name = "type_UNIQUE", IsUnique = true)]
public partial class Types
{
    [Key]
    [Column("type_id")]
    [MySqlCharSet("ascii")]
    [MySqlCollation("ascii_general_ci")]
    public Guid TypeId { get; set; }

    [Required]
    [Column("type")]
    [StringLength(100)]
    public string Type { get; set; }

    [ForeignKey("TypesTypeId")]
    [InverseProperty("TypesType")]
    public virtual ICollection<Aliases> AliasesAlias { get; set; } = new List<Aliases>();
}