// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EfCoreModelsLib.Models.Mysql;

[PrimaryKey("WritersId", "TitlesTitleId", "PersonsPersonId")]
[Index("PersonsPersonId", Name = "fk_Titles_has_Persons_Persons4_idx")]
[Index("TitlesTitleId", Name = "fk_Titles_has_Persons_Titles4_idx")]
public partial class Writers
{
    [Key]
    [Column("writers_id")]
    public Guid WritersId { get; set; }

    [Key]
    [Column("Titles_title_id")]
    public Guid TitlesTitleId { get; set; }

    [Key]
    [Column("Persons_person_id")]
    public Guid PersonsPersonId { get; set; }

    [ForeignKey("PersonsPersonId")]
    [InverseProperty("Writers")]
    public virtual Persons PersonsPerson { get; set; }

    [ForeignKey("TitlesTitleId")]
    [InverseProperty("Writers")]
    public virtual Titles TitlesTitle { get; set; }
}