// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

[PrimaryKey("TitlesTitleId", "PersonsPersonId")]
[Index("PersonsPersonId", Name = "fk_Titles_has_Persons_Persons3_idx")]
[Index("TitlesTitleId", Name = "fk_Titles_has_Persons_Titles3_idx")]
public partial class Actor
{
    [Key]
    [Column("Titles_title_id")]
    public Guid TitlesTitleId { get; set; }

    [Key]
    [Column("Persons_person_id")]
    public Guid PersonsPersonId { get; set; }

    [Required]
    [StringLength(100)]
    public string Role { get; set; }

    [ForeignKey("PersonsPersonId")]
    [InverseProperty("Actors")]
    public virtual Title PersonsPerson { get; set; }

    [ForeignKey("TitlesTitleId")]
    [InverseProperty("Actors")]
    public virtual Person TitlesTitle { get; set; }
}