// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

[PrimaryKey("Titles_title_id", "Persons_person_id")]
[Index("Persons_person_id", Name = "fk_Titles_has_Persons_Persons3_idx")]
[Index("Titles_title_id", Name = "fk_Titles_has_Persons_Titles3_idx")]
public partial class Actor
{
    [Key]
    public Guid Titles_title_id { get; set; }

    [Key]
    public Guid Persons_person_id { get; set; }

    [Required]
    [StringLength(100)]
    public string Role { get; set; }

    [ForeignKey("Persons_person_id")]
    [InverseProperty("Actors")]
    public virtual Title Persons_person { get; set; }

    [ForeignKey("Titles_title_id")]
    [InverseProperty("Actors")]
    public virtual Person Titles_title { get; set; }
}