// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

[Index("title_id", Name = "fk_title_akas_title_basics_idx")]
[Index("title", Name = "title_index")]
public partial class Alias
{
    [Key]
    public Guid alias_id { get; set; }

    public Guid title_id { get; set; }

    [Required]
    [StringLength(100)]
    public string region { get; set; }

    [Required]
    [StringLength(100)]
    public string language { get; set; }

    public bool is_original_title { get; set; }

    [Required]
    public string title { get; set; }

    [InverseProperty("Aliases_alias")]
    public virtual ICollection<Aliases_has_Attribute> Aliases_has_Attributes { get; set; } = new List<Aliases_has_Attribute>();

    [InverseProperty("Aliases_alias")]
    public virtual ICollection<Aliases_has_Type> Aliases_has_Types { get; set; } = new List<Aliases_has_Type>();

    [ForeignKey("title_id")]
    [InverseProperty("Aliases")]
    public virtual Title titleNavigation { get; set; }
}