// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

[PrimaryKey("AliasesAliasId", "AttributesAttributeId")]
[Table("Aliases_has_Attributes")]
[Index("AliasesAliasId", Name = "fk_Aliases_has_Attributes_Aliases1_idx")]
[Index("AttributesAttributeId", Name = "fk_Aliases_has_Attributes_Attributes1_idx")]
public partial class AliasesHasAttribute
{
    [Key]
    [Column("Aliases_alias_id")]
    public Guid AliasesAliasId { get; set; }

    [Key]
    [Column("Attributes_attribute_id")]
    public Guid AttributesAttributeId { get; set; }

    [ForeignKey("AliasesAliasId")]
    [InverseProperty("AliasesHasAttributes")]
    public virtual Alias AliasesAlias { get; set; }

    [ForeignKey("AttributesAttributeId")]
    [InverseProperty("AliasesHasAttributes")]
    public virtual Attribute AttributesAttribute { get; set; }
}