// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

[Index("TitleId", Name = "fk_title_akas_title_basics_idx")]
[Index("Title", Name = "title_index")]
public partial class Alias
{
    [Key]
    [Column("alias_id")]
    public Guid AliasId { get; set; }

    [Column("title_id")]
    public Guid TitleId { get; set; }

    [Required]
    [Column("region")]
    [StringLength(100)]
    public string Region { get; set; }

    [Required]
    [Column("language")]
    [StringLength(100)]
    public string Language { get; set; }

    [Column("is_original_title")]
    public bool IsOriginalTitle { get; set; }

    [Required]
    [Column("title")]
    public string Title { get; set; }

    [InverseProperty("AliasesAlias")]
    public virtual ICollection<AliasesHasAttribute> AliasesHasAttributes { get; set; } = new List<AliasesHasAttribute>();

    [InverseProperty("AliasesAlias")]
    public virtual ICollection<AliasesHasType> AliasesHasTypes { get; set; } = new List<AliasesHasType>();

    [ForeignKey("TitleId")]
    [InverseProperty("Aliases")]
    public virtual Title TitleNavigation { get; set; }
}