// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

[PrimaryKey("Aliases_alias_id", "Attributes_attribute_id")]
[Index("Aliases_alias_id", Name = "fk_Aliases_has_Attributes_Aliases1_idx")]
[Index("Attributes_attribute_id", Name = "fk_Aliases_has_Attributes_Attributes1_idx")]
public partial class Aliases_has_Attribute
{
    [Key]
    public Guid Aliases_alias_id { get; set; }

    [Key]
    public Guid Attributes_attribute_id { get; set; }

    [ForeignKey("Aliases_alias_id")]
    [InverseProperty("Aliases_has_Attributes")]
    public virtual Alias Aliases_alias { get; set; }

    [ForeignKey("Attributes_attribute_id")]
    [InverseProperty("Aliases_has_Attributes")]
    public virtual Attribute Attributes_attribute { get; set; }
}