// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

[PrimaryKey("AliasesAliasId", "TypesTypeId")]
[Table("Aliases_has_Types")]
[Index("AliasesAliasId", Name = "fk_Aliases_has_Types_Aliases1_idx")]
[Index("TypesTypeId", Name = "fk_Aliases_has_Types_Types1_idx")]
public partial class AliasesHasType
{
    [Key]
    [Column("Aliases_alias_id")]
    public Guid AliasesAliasId { get; set; }

    [Key]
    [Column("Types_type_id")]
    public Guid TypesTypeId { get; set; }

    [ForeignKey("AliasesAliasId")]
    [InverseProperty("AliasesHasTypes")]
    public virtual Alias AliasesAlias { get; set; }

    [ForeignKey("TypesTypeId")]
    [InverseProperty("AliasesHasTypes")]
    public virtual Type TypesType { get; set; }
}