// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

[Index("TitleId", Name = "fk_title_akas_title_basics_idx")]
[Index("Title", Name = "title_index")]
public partial class Alias
{
    [Key]
    [Column("alias_id", TypeName = "BINARY(16)")]
    public Guid AliasId { get; set; } = new Guid();

    [Column("title_id", TypeName = "BINARY(16)")]
    public Guid TitleId { get; set; } = new Guid();

    [Required]
    [Column("region")]
    [StringLength(100)]
    public string Region { get; set; }

    [Required]
    [Column("language")]
    [StringLength(100)]
    public string Language { get; set; }

    [Column("is_original_title")]
    public bool IsOriginalTitle { get; set; }

    [Required]
    [Column("title")]
    public string Title { get; set; }

    [ForeignKey("TitleId")]
    [InverseProperty("Aliases")]
    public virtual Title TitleNavigation { get; set; }

    [ForeignKey("AliasesAliasId")]
    [InverseProperty("AliasesAliases")]
    public virtual ICollection<Attribute> AttributesAttributes { get; set; } = new List<Attribute>();

    [ForeignKey("AliasesAliasId")]
    [InverseProperty("AliasesAliases")]
    public virtual ICollection<Type> TypesTypes { get; set; } = new List<Type>();
}