// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

[PrimaryKey("Aliases_alias_id", "Types_type_id")]
[Index("Aliases_alias_id", Name = "fk_Aliases_has_Types_Aliases1_idx")]
[Index("Types_type_id", Name = "fk_Aliases_has_Types_Types1_idx")]
public partial class Aliases_has_Type
{
    [Key]
    public Guid Aliases_alias_id { get; set; }

    [Key]
    public Guid Types_type_id { get; set; }

    [ForeignKey("Aliases_alias_id")]
    [InverseProperty("Aliases_has_Types")]
    public virtual Alias Aliases_alias { get; set; }

    [ForeignKey("Types_type_id")]
    [InverseProperty("Aliases_has_Types")]
    public virtual Type Types_type { get; set; }
}