// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

[Index("attribute", Name = "attribute_UNIQUE", IsUnique = true)]
public partial class Attribute
{
    [Key]
    public Guid attribute_id { get; set; }

    [Required]
    [StringLength(100)]
    public string attribute { get; set; }

    [InverseProperty("Attributes_attribute")]
    public virtual ICollection<Aliases_has_Attribute> Aliases_has_Attributes { get; set; } = new List<Aliases_has_Attribute>();
}