// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

[Index("title_id", Name = "fk_title_comments_title_basics1_idx")]
public partial class Comment
{
    [Key]
    public Guid comment_id { get; set; }

    public Guid title_id { get; set; }

    [Required]
    [StringLength(255)]
    public string comment { get; set; }

    [ForeignKey("title_id")]
    [InverseProperty("Comments")]
    public virtual Title title { get; set; }
}