// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

[Index("TitleId", Name = "fk_title_comments_title_basics1_idx")]
public partial class Comment
{
    [Key]
    [Column("comment_id")]
    public Guid CommentId { get; set; }

    [Column("title_id")]
    public Guid TitleId { get; set; }

    [Required]
    [Column("comment")]
    [StringLength(255)]
    public string Comment1 { get; set; }

    [ForeignKey("TitleId")]
    [InverseProperty("Comments")]
    public virtual Title Title { get; set; }
}