// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

[PrimaryKey("Titles_title_id", "Persons_person_id")]
[Index("Persons_person_id", Name = "fk_Titles_has_Persons_Persons1_idx")]
[Index("Titles_title_id", Name = "fk_Titles_has_Persons_Titles1_idx")]
public partial class Director
{
    [Key]
    public Guid Titles_title_id { get; set; }

    [Key]
    public Guid Persons_person_id { get; set; }

    [ForeignKey("Persons_person_id")]
    [InverseProperty("Directors")]
    public virtual Person Persons_person { get; set; }

    [ForeignKey("Titles_title_id")]
    [InverseProperty("Directors")]
    public virtual Title Titles_title { get; set; }
}