// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

[Index("TitleIdParent", Name = "fk_title_episodes_title_basics1")]
[Index("TitleIdChild", Name = "fk_title_episodes_title_basics2_idx")]
public partial class Episode
{
    [Key]
    [Column("episode_id",TypeName = "BINARY(16)")]
    public Guid EpisodeId { get; set; } = new Guid();

    [Column("title_id_parent", TypeName = "BINARY(16)")]
    public Guid TitleIdParent { get; set; } = new Guid();

    [Column("title_id_child", TypeName = "BINARY(16)")]
    public Guid TitleIdChild { get; set; } = new Guid();

    [Column("season_number")]
    public int SeasonNumber { get; set; }

    [Column("episode_number")]
    public int EpisodeNumber { get; set; }

    [ForeignKey("TitleIdChild")]
    [InverseProperty("EpisodeTitleIdChildNavigations")]
    public virtual Title TitleIdChildNavigation { get; set; }

    [ForeignKey("TitleIdParent")]
    [InverseProperty("EpisodeTitleIdParentNavigations")]
    public virtual Title TitleIdParentNavigation { get; set; }
}