// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

[Index("title_id_parent", Name = "fk_title_episodes_title_basics1")]
[Index("title_id_child", Name = "fk_title_episodes_title_basics2_idx")]
public partial class Episode
{
    [Key]
    public Guid episode_id { get; set; }

    public Guid? title_id_parent { get; set; }

    public Guid? title_id_child { get; set; }

    public int season_number { get; set; }

    public int episode_number { get; set; }

    [ForeignKey("title_id_child")]
    [InverseProperty("Episodetitle_id_childNavigations")]
    public virtual Title title_id_childNavigation { get; set; }

    [ForeignKey("title_id_parent")]
    [InverseProperty("Episodetitle_id_parentNavigations")]
    public virtual Title title_id_parentNavigation { get; set; }
}