// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

[Index("genre", Name = "genre_UNIQUE", IsUnique = true)]
public partial class Genre
{
    [Key]
    public Guid genre_id { get; set; }

    [Required]
    [StringLength(100)]
    public string genre { get; set; }

    [InverseProperty("Genres_genre")]
    public virtual ICollection<Titles_has_Genre> Titles_has_Genres { get; set; } = new List<Titles_has_Genre>();
}