// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

public partial class ImdbContext : DbContext
{
    public ImdbContext(DbContextOptions<ImdbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Actor> Actors { get; set; }

    public virtual DbSet<Alias> Aliases { get; set; }

    public virtual DbSet<Attribute> Attributes { get; set; }

    public virtual DbSet<Comment> Comments { get; set; }

    public virtual DbSet<Episode> Episodes { get; set; }

    public virtual DbSet<Genre> Genres { get; set; }

    public virtual DbSet<Logging> Loggings { get; set; }

    public virtual DbSet<Person> Persons { get; set; }

    public virtual DbSet<Profession> Professions { get; set; }

    public virtual DbSet<Rating> Ratings { get; set; }

    public virtual DbSet<Title> Titles { get; set; }

    public virtual DbSet<Type> Types { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .UseCollation("utf8mb3_general_ci")
            .HasCharSet("utf8mb3");

        modelBuilder.Entity<Actor>(entity =>
        {
            entity.HasKey(e => new { e.TitlesTitleId, e.PersonsPersonId })
                .HasName("PRIMARY")
                .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

            entity.HasOne(d => d.PersonsPerson).WithMany(p => p.Actors)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_Titles_has_Persons_Persons3");

            entity.HasOne(d => d.TitlesTitle).WithMany(p => p.Actors)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_Titles_has_Persons_Titles3");
        });

        modelBuilder.Entity<Alias>(entity =>
        {
            entity.HasKey(e => e.AliasId).HasName("PRIMARY");

            entity.Property(e => e.AliasId).HasDefaultValueSql("uuid_to_bin(uuid(),1)");

            entity.HasOne(d => d.TitleNavigation).WithMany(p => p.Aliases)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_title_akas_title_basics");

            entity.HasMany(d => d.AttributesAttributes).WithMany(p => p.AliasesAliases)
                .UsingEntity<Dictionary<string, object>>(
                    "AliasesHasAttribute",
                    r => r.HasOne<Attribute>().WithMany()
                        .HasForeignKey("AttributesAttributeId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("fk_Aliases_has_Attributes_Attributes1"),
                    l => l.HasOne<Alias>().WithMany()
                        .HasForeignKey("AliasesAliasId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("fk_Aliases_has_Attributes_Aliases1"),
                    j =>
                    {
                        j.HasKey("AliasesAliasId", "AttributesAttributeId")
                            .HasName("PRIMARY")
                            .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });
                        j.ToTable("Aliases_has_Attributes");
                        j.HasIndex(new[] { "AliasesAliasId" }, "fk_Aliases_has_Attributes_Aliases1_idx");
                        j.HasIndex(new[] { "AttributesAttributeId" }, "fk_Aliases_has_Attributes_Attributes1_idx");
                        j.IndexerProperty<Guid>("AliasesAliasId").HasColumnName("Aliases_alias_id");
                        j.IndexerProperty<Guid>("AttributesAttributeId").HasColumnName("Attributes_attribute_id");
                    });

            entity.HasMany(d => d.TypesTypes).WithMany(p => p.AliasesAliases)
                .UsingEntity<Dictionary<string, object>>(
                    "AliasesHasType",
                    r => r.HasOne<Type>().WithMany()
                        .HasForeignKey("TypesTypeId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("fk_Aliases_has_Types_Types1"),
                    l => l.HasOne<Alias>().WithMany()
                        .HasForeignKey("AliasesAliasId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("fk_Aliases_has_Types_Aliases1"),
                    j =>
                    {
                        j.HasKey("AliasesAliasId", "TypesTypeId")
                            .HasName("PRIMARY")
                            .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });
                        j.ToTable("Aliases_has_Types");
                        j.HasIndex(new[] { "AliasesAliasId" }, "fk_Aliases_has_Types_Aliases1_idx");
                        j.HasIndex(new[] { "TypesTypeId" }, "fk_Aliases_has_Types_Types1_idx");
                        j.IndexerProperty<Guid>("AliasesAliasId").HasColumnName("Aliases_alias_id");
                        j.IndexerProperty<Guid>("TypesTypeId").HasColumnName("Types_type_id");
                    });
        });

        modelBuilder.Entity<Attribute>(entity =>
        {
            entity.HasKey(e => e.AttributeId).HasName("PRIMARY");

            entity.Property(e => e.AttributeId).HasDefaultValueSql("uuid_to_bin(uuid(),1)");
        });

        modelBuilder.Entity<Comment>(entity =>
        {
            entity.HasKey(e => e.CommentId).HasName("PRIMARY");

            entity.Property(e => e.CommentId).HasDefaultValueSql("uuid_to_bin(uuid(),1)");

            entity.HasOne(d => d.Title).WithMany(p => p.Comments)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_title_comments_title_basics1");
        });

        modelBuilder.Entity<Episode>(entity =>
        {
            entity.HasKey(e => e.EpisodeId).HasName("PRIMARY");

            entity.Property(e => e.EpisodeId).HasDefaultValueSql("uuid_to_bin(uuid(),1)");

            entity.HasOne(d => d.TitleIdChildNavigation).WithMany(p => p.EpisodeTitleIdChildNavigations).HasConstraintName("fk_title_episodes_title_basics2");

            entity.HasOne(d => d.TitleIdParentNavigation).WithMany(p => p.EpisodeTitleIdParentNavigations).HasConstraintName("fk_title_episodes_title_basics1");
        });

        modelBuilder.Entity<Genre>(entity =>
        {
            entity.HasKey(e => e.GenreId).HasName("PRIMARY");

            entity.Property(e => e.GenreId).HasDefaultValueSql("uuid_to_bin(uuid(),1)");
        });

        modelBuilder.Entity<Logging>(entity =>
        {
            entity.HasKey(e => e.LoggingId).HasName("PRIMARY");

            entity.Property(e => e.LoggingId).HasDefaultValueSql("uuid_to_bin(uuid(),1)");
            entity.Property(e => e.ExecutedAt).HasDefaultValueSql("now(6)");
        });

        modelBuilder.Entity<Person>(entity =>
        {
            entity.HasKey(e => e.PersonId).HasName("PRIMARY");

            entity.Property(e => e.PersonId).HasDefaultValueSql("uuid_to_bin(uuid(),1)");
        });

        modelBuilder.Entity<Profession>(entity =>
        {
            entity.HasKey(e => e.ProfessionId).HasName("PRIMARY");

            entity.Property(e => e.ProfessionId).HasDefaultValueSql("uuid_to_bin(uuid(),1)");

            entity.HasOne(d => d.Person).WithMany(p => p.Professions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_Professions_Persons1");
        });

        modelBuilder.Entity<Rating>(entity =>
        {
            entity.HasKey(e => e.RatingId).HasName("PRIMARY");

            entity.Property(e => e.RatingId).HasDefaultValueSql("uuid_to_bin(uuid(),1)");

            entity.HasOne(d => d.Title).WithMany(p => p.Ratings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_title_ratings_title_basics1");
        });

        modelBuilder.Entity<Title>(entity =>
        {
            entity.HasKey(e => e.TitleId).HasName("PRIMARY");

            entity.Property(e => e.TitleId).HasDefaultValueSql("uuid_to_bin(uuid(),1)");

            entity.HasMany(d => d.GenresGenres).WithMany(p => p.TitlesTitles)
                .UsingEntity<Dictionary<string, object>>(
                    "TitlesHasGenre",
                    r => r.HasOne<Genre>().WithMany()
                        .HasForeignKey("GenresGenreId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("fk_Titles_has_Genres_Genres1"),
                    l => l.HasOne<Title>().WithMany()
                        .HasForeignKey("TitlesTitleId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("fk_Titles_has_Genres_Titles1"),
                    j =>
                    {
                        j.HasKey("TitlesTitleId", "GenresGenreId")
                            .HasName("PRIMARY")
                            .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });
                        j.ToTable("Titles_has_Genres");
                        j.HasIndex(new[] { "GenresGenreId" }, "fk_Titles_has_Genres_Genres1_idx");
                        j.HasIndex(new[] { "TitlesTitleId" }, "fk_Titles_has_Genres_Titles1_idx");
                        j.IndexerProperty<Guid>("TitlesTitleId").HasColumnName("Titles_title_id");
                        j.IndexerProperty<Guid>("GenresGenreId").HasColumnName("Genres_genre_id");
                    });

            entity.HasMany(d => d.PersonsPeople).WithMany(p => p.TitlesTitles)
                .UsingEntity<Dictionary<string, object>>(
                    "Director",
                    r => r.HasOne<Person>().WithMany()
                        .HasForeignKey("PersonsPersonId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("fk_Titles_has_Persons_Persons1"),
                    l => l.HasOne<Title>().WithMany()
                        .HasForeignKey("TitlesTitleId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("fk_Titles_has_Persons_Titles1"),
                    j =>
                    {
                        j.HasKey("TitlesTitleId", "PersonsPersonId")
                            .HasName("PRIMARY")
                            .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });
                        j.ToTable("Directors");
                        j.HasIndex(new[] { "PersonsPersonId" }, "fk_Titles_has_Persons_Persons1_idx");
                        j.HasIndex(new[] { "TitlesTitleId" }, "fk_Titles_has_Persons_Titles1_idx");
                        j.IndexerProperty<Guid>("TitlesTitleId").HasColumnName("Titles_title_id");
                        j.IndexerProperty<Guid>("PersonsPersonId").HasColumnName("Persons_person_id");
                    });

            entity.HasMany(d => d.PersonsPeople1).WithMany(p => p.TitlesTitles1)
                .UsingEntity<Dictionary<string, object>>(
                    "Writer",
                    r => r.HasOne<Person>().WithMany()
                        .HasForeignKey("PersonsPersonId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("fk_Titles_has_Persons_Persons4"),
                    l => l.HasOne<Title>().WithMany()
                        .HasForeignKey("TitlesTitleId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("fk_Titles_has_Persons_Titles4"),
                    j =>
                    {
                        j.HasKey("TitlesTitleId", "PersonsPersonId")
                            .HasName("PRIMARY")
                            .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });
                        j.ToTable("Writers");
                        j.HasIndex(new[] { "PersonsPersonId" }, "fk_Titles_has_Persons_Persons4_idx");
                        j.HasIndex(new[] { "TitlesTitleId" }, "fk_Titles_has_Persons_Titles4_idx");
                        j.IndexerProperty<Guid>("TitlesTitleId").HasColumnName("Titles_title_id");
                        j.IndexerProperty<Guid>("PersonsPersonId").HasColumnName("Persons_person_id");
                    });

            entity.HasMany(d => d.PersonsPeopleNavigation).WithMany(p => p.TitlesTitlesNavigation)
                .UsingEntity<Dictionary<string, object>>(
                    "KnownFor",
                    r => r.HasOne<Person>().WithMany()
                        .HasForeignKey("PersonsPersonId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("fk_Titles_has_Persons_Persons2"),
                    l => l.HasOne<Title>().WithMany()
                        .HasForeignKey("TitlesTitleId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("fk_Titles_has_Persons_Titles2"),
                    j =>
                    {
                        j.HasKey("TitlesTitleId", "PersonsPersonId")
                            .HasName("PRIMARY")
                            .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });
                        j.ToTable("Known_for");
                        j.HasIndex(new[] { "PersonsPersonId" }, "fk_Titles_has_Persons_Persons2_idx");
                        j.HasIndex(new[] { "TitlesTitleId" }, "fk_Titles_has_Persons_Titles2_idx");
                        j.IndexerProperty<Guid>("TitlesTitleId").HasColumnName("Titles_title_id");
                        j.IndexerProperty<Guid>("PersonsPersonId").HasColumnName("Persons_person_id");
                    });
        });

        modelBuilder.Entity<Type>(entity =>
        {
            entity.HasKey(e => e.TypeId).HasName("PRIMARY");

            entity.Property(e => e.TypeId).HasDefaultValueSql("uuid_to_bin(uuid(),1)");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}