// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

[PrimaryKey("TitlesTitleId", "PersonsPersonId")]
[Table("Known_for")]
[Index("PersonsPersonId", Name = "fk_Titles_has_Persons_Persons2_idx")]
[Index("TitlesTitleId", Name = "fk_Titles_has_Persons_Titles2_idx")]
public partial class KnownFor
{
    [Key]
    [Column("Titles_title_id")]
    public Guid TitlesTitleId { get; set; }

    [Key]
    [Column("Persons_person_id")]
    public Guid PersonsPersonId { get; set; }

    [ForeignKey("PersonsPersonId")]
    [InverseProperty("KnownFors")]
    public virtual Person PersonsPerson { get; set; }

    [ForeignKey("TitlesTitleId")]
    [InverseProperty("KnownFors")]
    public virtual Title TitlesTitle { get; set; }
}