// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

[Index("executed_at", Name = "executed_at_index")]
[Index("table_name", Name = "table_name_index")]
public partial class Logging
{
    [Key]
    public Guid logging_id { get; set; }

    [Required]
    [StringLength(100)]
    public string table_name { get; set; }

    [Required]
    [Column(TypeName = "enum('INSERT','UPDATE','DELETE')")]
    public string command { get; set; }

    [Column(TypeName = "json")]
    public string new_value { get; set; }

    [Column(TypeName = "json")]
    public string old_value { get; set; }

    [StringLength(100)]
    public string executed_by { get; set; }

    [MaxLength(6)]
    public DateTime executed_at { get; set; }
}