// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

[Table("name_basics")]
public partial class NameBasic
{
    [Key]
    [Column("nconst")]
    [StringLength(100)]
    public string Nconst { get; set; }

    [Required]
    [Column("primary_name")]
    [StringLength(255)]
    public string PrimaryName { get; set; }

    [Column("birth_year")]
    public int BirthYear { get; set; }

    [Column("end_year")]
    public int? EndYear { get; set; }

    [InverseProperty("NconstNavigation")]
    public virtual ICollection<TitlePrincipal> TitlePrincipals { get; set; } = new List<TitlePrincipal>();

    [ForeignKey("Nconst")]
    [InverseProperty("Nconsts")]
    public virtual ICollection<TitleBasic> Tconsts { get; set; } = new List<TitleBasic>();
}