// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

public partial class Person
{
    [Key]
    [Column("person_id")]
    public Guid PersonId { get; set; }

    [Required]
    [Column("name")]
    [StringLength(255)]
    public string Name { get; set; }

    [Column("birth_year", TypeName = "year")]
    public short BirthYear { get; set; }

    [Column("end_year", TypeName = "year")]
    public short? EndYear { get; set; }

    [InverseProperty("TitlesTitle")]
    public virtual ICollection<Actor> Actors { get; set; } = new List<Actor>();

    [InverseProperty("PersonsPerson")]
    public virtual ICollection<Director> Directors { get; set; } = new List<Director>();

    [InverseProperty("PersonsPerson")]
    public virtual ICollection<KnownFor> KnownFors { get; set; } = new List<KnownFor>();

    [InverseProperty("Person")]
    public virtual ICollection<Profession> Professions { get; set; } = new List<Profession>();

    [InverseProperty("PersonsPerson")]
    public virtual ICollection<Writer> Writers { get; set; } = new List<Writer>();
}