// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

public partial class Person
{
    [Key]
    public Guid person_id { get; set; }

    [Required]
    [StringLength(255)]
    public string name { get; set; }

    [Column(TypeName = "year")]
    public short birth_year { get; set; }

    [Column(TypeName = "year")]
    public short? end_year { get; set; }

    [InverseProperty("Titles_title")]
    public virtual ICollection<Actor> Actors { get; set; } = new List<Actor>();

    [InverseProperty("Persons_person")]
    public virtual ICollection<Director> Directors { get; set; } = new List<Director>();

    [InverseProperty("Persons_person")]
    public virtual ICollection<Known_for> Known_fors { get; set; } = new List<Known_for>();

    [InverseProperty("person")]
    public virtual ICollection<Profession> Professions { get; set; } = new List<Profession>();

    [InverseProperty("Persons_person")]
    public virtual ICollection<Writer> Writers { get; set; } = new List<Writer>();
}