// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

[Index("PersonId", Name = "fk_Professions_Persons1_idx")]
[Index("Profession1", Name = "profession_UNIQUE", IsUnique = true)]
public partial class Profession
{
    [Key]
    [Column("profession_id", TypeName = "BINARY(16)")]
    public Guid ProfessionId { get; set; } = new Guid();

    [Column("person_id", TypeName = "BINARY(16)")]
    public Guid PersonId { get; set; } = new Guid();

    [Required]
    [Column("profession")]
    [StringLength(45)]
    public string Profession1 { get; set; }

    [ForeignKey("PersonId")]
    [InverseProperty("Professions")]
    public virtual Person Person { get; set; }
}