// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

[Index("person_id", Name = "fk_Professions_Persons1_idx")]
[Index("profession", Name = "profession_UNIQUE", IsUnique = true)]
public partial class Profession
{
    [Key]
    public Guid profession_id { get; set; }

    public Guid person_id { get; set; }

    [Required]
    [StringLength(45)]
    public string profession { get; set; }

    [ForeignKey("person_id")]
    [InverseProperty("Professions")]
    public virtual Person person { get; set; }
}