// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

[Index("title_id", Name = "fk_title_ratings_title_basics1")]
public partial class Rating
{
    [Key]
    public Guid rating_id { get; set; }

    public Guid title_id { get; set; }

    public double average_rating { get; set; }

    public int num_votes { get; set; }

    [ForeignKey("title_id")]
    [InverseProperty("Ratings")]
    public virtual Title title { get; set; }
}