// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

[Index("TitleId", Name = "fk_title_ratings_title_basics1")]
public partial class Rating
{
    [Key]
    [Column("rating_id")]
    public Guid RatingId { get; set; }

    [Column("title_id")]
    public Guid TitleId { get; set; }

    [Column("average_rating")]
    public double AverageRating { get; set; }

    [Column("num_votes")]
    public int NumVotes { get; set; }

    [ForeignKey("TitleId")]
    [InverseProperty("Ratings")]
    public virtual Title Title { get; set; }
}