// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

[Table("title_ratings")]
[Index("Tconst", Name = "fk_title_ratings_title_basics1")]
public partial class TitleRating
{
    [Key]
    [Column("id_rating")]
    public int IdRating { get; set; }

    [Required]
    [Column("tconst")]
    [StringLength(100)]
    public string Tconst { get; set; }

    [Column("average_rating")]
    public double AverageRating { get; set; }

    [Column("num_votes")]
    public int NumVotes { get; set; }

    [ForeignKey("Tconst")]
    [InverseProperty("TitleRatings")]
    public virtual TitleBasic TconstNavigation { get; set; }
}