// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

[PrimaryKey("ParentTconst", "Tconst")]
[Table("title_episodes")]
[Index("Tconst", Name = "fk_title_episodes_title_basics1")]
[Index("ParentTconst", Name = "fk_title_episodes_title_basics2_idx")]
public partial class TitleEpisode
{
    [Key]
    [Column("tconst")]
    [StringLength(100)]
    public string Tconst { get; set; }

    [Key]
    [Column("parent_tconst")]
    [StringLength(100)]
    public string ParentTconst { get; set; }

    [Column("season_number")]
    public int SeasonNumber { get; set; }

    [Column("episode_number")]
    public int EpisodeNumber { get; set; }

    [ForeignKey("ParentTconst")]
    [InverseProperty("TitleEpisodeParentTconstNavigations")]
    public virtual TitleBasic ParentTconstNavigation { get; set; }

    [ForeignKey("Tconst")]
    [InverseProperty("TitleEpisodeTconstNavigations")]
    public virtual TitleBasic TconstNavigation { get; set; }
}