// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

[PrimaryKey("Titles_title_id", "Genres_genre_id")]
[Index("Genres_genre_id", Name = "fk_Titles_has_Genres_Genres1_idx")]
[Index("Titles_title_id", Name = "fk_Titles_has_Genres_Titles1_idx")]
public partial class Titles_has_Genre
{
    [Key]
    public Guid Titles_title_id { get; set; }

    [Key]
    public Guid Genres_genre_id { get; set; }

    [ForeignKey("Genres_genre_id")]
    [InverseProperty("Titles_has_Genres")]
    public virtual Genre Genres_genre { get; set; }

    [ForeignKey("Titles_title_id")]
    [InverseProperty("Titles_has_Genres")]
    public virtual Title Titles_title { get; set; }
}