// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

[Table("title_types")]
public partial class TitleType
{
    [Key]
    [Column("id_types")]
    public int IdTypes { get; set; }

    [Required]
    [Column("type")]
    [StringLength(100)]
    public string Type { get; set; }

    [ForeignKey("IdTypes")]
    [InverseProperty("IdTypes")]
    public virtual ICollection<TitleAka> IdAkas { get; set; } = new List<TitleAka>();
}