// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

[PrimaryKey("TitlesTitleId", "GenresGenreId")]
[Table("Titles_has_Genres")]
[Index("GenresGenreId", Name = "fk_Titles_has_Genres_Genres1_idx")]
[Index("TitlesTitleId", Name = "fk_Titles_has_Genres_Titles1_idx")]
public partial class TitlesHasGenre
{
    [Key]
    [Column("Titles_title_id")]
    public Guid TitlesTitleId { get; set; }

    [Key]
    [Column("Genres_genre_id")]
    public Guid GenresGenreId { get; set; }

    [ForeignKey("GenresGenreId")]
    [InverseProperty("TitlesHasGenres")]
    public virtual Genre GenresGenre { get; set; }

    [ForeignKey("TitlesTitleId")]
    [InverseProperty("TitlesHasGenres")]
    public virtual Title TitlesTitle { get; set; }
}