// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

[Table("title_genres")]
public partial class TitleGenre
{
    [Key]
    [Column("id_genre")]
    public int IdGenre { get; set; }

    [Required]
    [Column("genre")]
    [StringLength(100)]
    public string Genre { get; set; }

    [ForeignKey("IdGenre")]
    [InverseProperty("IdGenres")]
    public virtual ICollection<TitleBasic> Tconsts { get; set; } = new List<TitleBasic>();
}