// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

[Table("title_akas")]
[Index("Tconst", Name = "fk_title_akas_title_basics_idx")]
public partial class TitleAka
{
    [Key]
    [Column("id_akas")]
    public int IdAkas { get; set; }

    [Required]
    [Column("tconst")]
    [StringLength(100)]
    public string Tconst { get; set; }

    [Required]
    [Column("region")]
    [StringLength(100)]
    public string Region { get; set; }

    [Required]
    [Column("language")]
    [StringLength(100)]
    public string Language { get; set; }

    [Column("is_original_title")]
    public sbyte IsOriginalTitle { get; set; }

    [ForeignKey("Tconst")]
    [InverseProperty("TitleAkas")]
    public virtual TitleBasic TconstNavigation { get; set; }

    [ForeignKey("IdAkas")]
    [InverseProperty("IdAkas")]
    public virtual ICollection<TitleAttribute> IdAttributes { get; set; } = new List<TitleAttribute>();

    [ForeignKey("IdAkas")]
    [InverseProperty("IdAkas")]
    public virtual ICollection<TitleType> IdTypes { get; set; } = new List<TitleType>();
}