// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

[Table("title_attributes")]
public partial class TitleAttribute
{
    [Key]
    [Column("id_attribute")]
    public int IdAttribute { get; set; }

    [Required]
    [Column("attribute")]
    [StringLength(100)]
    public string Attribute { get; set; }

    [ForeignKey("IdAttribute")]
    [InverseProperty("IdAttributes")]
    public virtual ICollection<TitleAka> IdAkas { get; set; } = new List<TitleAka>();
}