// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

[Table("title_basics")]
public partial class TitleBasic
{
    [Key]
    [Column("tconst")]
    [StringLength(100)]
    public string Tconst { get; set; }

    [Required]
    [Column("title_type")]
    [StringLength(100)]
    public string TitleType { get; set; }

    [Required]
    [Column("primary_title")]
    [StringLength(255)]
    public string PrimaryTitle { get; set; }

    [Required]
    [Column("original_title")]
    [StringLength(255)]
    public string OriginalTitle { get; set; }

    [Column("is_adult")]
    public sbyte IsAdult { get; set; }

    [Column("start_year")]
    public int StartYear { get; set; }

    [Column("end_year")]
    public int? EndYear { get; set; }

    [Column("runtime_minutes")]
    public int? RuntimeMinutes { get; set; }

    [InverseProperty("TconstNavigation")]
    public virtual ICollection<TitleAka> TitleAkas { get; set; } = new List<TitleAka>();

    [InverseProperty("TconstNavigation")]
    public virtual ICollection<TitleComment> TitleComments { get; set; } = new List<TitleComment>();

    [InverseProperty("ParentTconstNavigation")]
    public virtual ICollection<TitleEpisode> TitleEpisodeParentTconstNavigations { get; set; } = new List<TitleEpisode>();

    [InverseProperty("TconstNavigation")]
    public virtual ICollection<TitleEpisode> TitleEpisodeTconstNavigations { get; set; } = new List<TitleEpisode>();

    [InverseProperty("TconstNavigation")]
    public virtual ICollection<TitlePrincipal> TitlePrincipals { get; set; } = new List<TitlePrincipal>();

    [InverseProperty("TconstNavigation")]
    public virtual ICollection<TitleRating> TitleRatings { get; set; } = new List<TitleRating>();

    [ForeignKey("Tconst")]
    [InverseProperty("Tconsts")]
    public virtual ICollection<TitleGenre> IdGenres { get; set; } = new List<TitleGenre>();

    [ForeignKey("Tconst")]
    [InverseProperty("Tconsts")]
    public virtual ICollection<NameBasic> Nconsts { get; set; } = new List<NameBasic>();
}