// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

[Index("OriginalTitle", Name = "original_title_index")]
[Index("PrimaryTitle", Name = "primary_title_index")]
[Index("TitleType", Name = "title_type_index")]
public partial class Title
{
    [Key]
    [Column("title_id", TypeName = "BINARY(16)")]
    public Guid TitleId { get; set; } = new Guid();

    [Required]
    [Column("title_type")]
    [StringLength(100)]
    public string TitleType { get; set; }

    [Required]
    [Column("primary_title")]
    public string PrimaryTitle { get; set; }

    [Required]
    [Column("original_title")]
    public string OriginalTitle { get; set; }

    [Column("is_adult")]
    public bool IsAdult { get; set; }

    [Column("start_year", TypeName = "year")]
    public short StartYear { get; set; }

    [Column("end_year", TypeName = "year")]
    public short? EndYear { get; set; }

    [Column("runtime_minutes")]
    public int? RuntimeMinutes { get; set; }

    [InverseProperty("PersonsPerson")]
    public virtual ICollection<Actor> Actors { get; set; } = new List<Actor>();

    [InverseProperty("TitleNavigation")]
    public virtual ICollection<Alias> Aliases { get; set; } = new List<Alias>();

    [InverseProperty("Title")]
    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    [InverseProperty("TitleIdChildNavigation")]
    public virtual ICollection<Episode> EpisodeTitleIdChildNavigations { get; set; } = new List<Episode>();

    [InverseProperty("TitleIdParentNavigation")]
    public virtual ICollection<Episode> EpisodeTitleIdParentNavigations { get; set; } = new List<Episode>();

    [InverseProperty("Title")]
    public virtual ICollection<Rating> Ratings { get; set; } = new List<Rating>();

    [ForeignKey("TitlesTitleId")]
    [InverseProperty("TitlesTitles")]
    public virtual ICollection<Genre> GenresGenres { get; set; } = new List<Genre>();

    [ForeignKey("TitlesTitleId")]
    [InverseProperty("TitlesTitles")]
    public virtual ICollection<Person> PersonsPeople { get; set; } = new List<Person>();

    [ForeignKey("TitlesTitleId")]
    [InverseProperty("TitlesTitles1")]
    public virtual ICollection<Person> PersonsPeople1 { get; set; } = new List<Person>();

    [ForeignKey("TitlesTitleId")]
    [InverseProperty("TitlesTitlesNavigation")]
    public virtual ICollection<Person> PersonsPeopleNavigation { get; set; } = new List<Person>();
}