// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

[Table("title_comments")]
[Index("Tconst", Name = "fk_title_comments_title_basics1_idx")]
public partial class TitleComment
{
    [Key]
    [Column("id_comment")]
    public int IdComment { get; set; }

    [Required]
    [Column("tconst")]
    [StringLength(100)]
    public string Tconst { get; set; }

    [Required]
    [Column("comment")]
    [StringLength(255)]
    public string Comment { get; set; }

    [ForeignKey("Tconst")]
    [InverseProperty("TitleComments")]
    public virtual TitleBasic TconstNavigation { get; set; }
}