// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

[PrimaryKey("Nconst", "Tconst")]
[Table("title_principals")]
[Index("Tconst", Name = "fk_title_principals_title_basics1_idx")]
public partial class TitlePrincipal
{
    [Key]
    [Column("nconst")]
    [StringLength(100)]
    public string Nconst { get; set; }

    [Key]
    [Column("tconst")]
    [StringLength(100)]
    public string Tconst { get; set; }

    [Required]
    [Column("category")]
    [StringLength(100)]
    public string Category { get; set; }

    [Required]
    [Column("job")]
    [StringLength(100)]
    public string Job { get; set; }

    [Column("characters")]
    [StringLength(100)]
    public string Characters { get; set; }

    [ForeignKey("Nconst")]
    [InverseProperty("TitlePrincipals")]
    public virtual NameBasic NconstNavigation { get; set; }

    [ForeignKey("Tconst")]
    [InverseProperty("TitlePrincipals")]
    public virtual TitleBasic TconstNavigation { get; set; }
}