// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

[Index("Type1", Name = "type_UNIQUE", IsUnique = true)]
public partial class Type
{
    [Key]
    [Column("type_id")]
    public Guid TypeId { get; set; }

    [Required]
    [Column("type")]
    [StringLength(100)]
    public string Type1 { get; set; }

    [InverseProperty("TypesType")]
    public virtual ICollection<AliasesHasType> AliasesHasTypes { get; set; } = new List<AliasesHasType>();
}