// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SeedData.Models;

[Index("type", Name = "type_UNIQUE", IsUnique = true)]
public partial class Type
{
    [Key]
    public Guid type_id { get; set; }

    [Required]
    [StringLength(100)]
    public string type { get; set; }

    [InverseProperty("Types_type")]
    public virtual ICollection<Aliases_has_Type> Aliases_has_Types { get; set; } = new List<Aliases_has_Type>();
}