#!/bin/sh

echo "
╔═══════════════════════════════════╗
║     RUNNING HUSKY PRE-COMMIT      ║
╚═══════════════════════════════════╝
"

# Build frontend project
npm run build

# Run tests
npm run test
