name: Pull Request Workflow

on:
  pull_request:

jobs:
  test:
    name: Just a Test Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run a Simple Command
        run: echo "This is a test job for pull requests."
